const GET_DOGS = "GET_DOGS";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const FILTER_BY_TEMPERAMENT = "FILTER_BY_TEMPERAMENT";
const GET_DOGS_BY_NAME = "GET_DOGS_BY_NAME";
const ORDER_BY_NAME = "ORDER_BY_NAME";
const ORDER_BY_WEIGHT = "ORDER_BY_WEIGHT";
const GET_DOGS_BY_ID = "GET_DOGS_BY_ID";
